/* Warning: This file is generated by /data/home/olly/tmp/xapian-svn-snapshot/tags/1.1.4/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_lockfileumask1();
extern bool test_totaldoclen1();
extern bool test_dbstats1();
extern bool test_alldocspl3();
extern bool test_modifiedpostlist1();
extern bool test_doclenaftercommit1();
extern bool test_valuesaftercommit1();
extern bool test_lockfilefd0or1();
extern bool test_matchdecider4();
extern bool test_replacedoc7();
extern bool test_replacedoc8();
